workflows:
  android-app:
    name: Android CI
    max_build_duration: 60
    environment:
      java: 17

    scripts:
      - name: Show repo layout
        script: |
          ls -la
          ls -la gradle || true
          ls -la gradle/wrapper || true

      - name: Verify Gradle wrapper (auto-fix if jar is tiny/missing)
        script: |
          set -euo pipefail
          WRAP_DIR="gradle/wrapper"
          WRAP_JAR="${WRAP_DIR}/gradle-wrapper.jar"
          WRAP_PROPS="${WRAP_DIR}/gradle-wrapper.properties"
          GRADLE_VERSION="8.9"
          DIST_BIN_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
          DIST_ALL_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-all.zip"

          mkdir -p "${WRAP_DIR}"

          size=0
          if [ -f "${WRAP_JAR}" ]; then
            size=$(wc -c < "${WRAP_JAR}" || echo 0)
          fi
          echo "Current wrapper jar size: ${size} bytes"

          if [ ! -f "${WRAP_JAR}" ] || [ "${size}" -lt 60000 ]; then
            echo "Fetching proper gradle-wrapper *.jar from ${DIST_ALL_URL} ..."
            curl -fL -o gradle-all.zip "${DIST_ALL_URL}"
            unzip -j gradle-all.zip "gradle-${GRADLE_VERSION}/lib/plugins/gradle-wrapper-*.jar" -d "${WRAP_DIR}"
            mv "${WRAP_DIR}"/gradle-wrapper-*.jar "${WRAP_JAR}"
          fi

          echo "Listing contents inside wrapper jar..."
          unzip -l "${WRAP_JAR}" | head -n 30 || true

          # Warn instead of failing hard on grep
          unzip -l "${WRAP_JAR}" | grep "GradleWrapperMain.class" || echo "⚠ GradleWrapperMain.class not found in jar listing"
          unzip -l "${WRAP_JAR}" | grep "IDownload.class"        || echo "⚠ IDownload.class not found in jar listing"

          if [ -f "${WRAP_PROPS}" ]; then
            sed -i "s#^distributionUrl=.*#distributionUrl=${DIST_BIN_URL}#g" "${WRAP_PROPS}" || true
          fi

      - name: Gradle wrapper permissions
        script: |
          chmod +x ./gradlew
          sed -i 's/\r$//' gradlew

      - name: Print versions
        script: |
          java -version
          ./gradlew -v || echo "⚠ gradlew -v failed (will try build anyway)"

      - name: Clean & build Debug APK
        script: |
          ./gradlew --no-daemon clean :app:assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper