workflows:
  android-ci:
    name: Android CI
    max_build_duration: 60
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      java: 17
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Clean and assemble Debug
        script: ./gradlew clean :app:assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk