workflows:
  android-app:
    name: Build Android Debug
    max_build_duration: 60
    environment:
      java: 17
      vars:
        WRAPPER_GRADLE_VERSION: "8.9"
    scripts:
      - name: Gradle wrapper permissions
        script: chmod +x ./gradlew
      - name: Clean & build Debug APK
        script: ./gradlew clean assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper