workflows:
  android-firebase-workflow:
    name: Build Android App + Firebase Hosting
    max_build_duration: 60
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk-linux
        FIREBASE_TOKEN: Encrypted(your-token-here)
      java: 17

    scripts:
      - name: Install dependencies
        script: ./gradlew dependencies

      - name: Build Debug APK
        script: ./gradlew assembleDebug

      - name: Install Firebase CLI
        script: npm install -g firebase-tools

      - name: Deploy Firebase Hosting
        script: firebase deploy --only hosting --token $FIREBASE_TOKEN

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "liamhigh78@gmail.com"

