name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - 'build.gradle*'
      - 'settings.gradle*'
      - '.github/workflows/android.yml'

concurrency:
  group: android-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Hard refresh the Gradle wrapper + caches to avoid the WrapperMain not found issue
      - name: Clean Gradle caches (first run safety)
        run: |
          rm -rf ~/.gradle/wrapper ~/.gradle/caches || true

      # (Optional) Gradle build cache/scan setup for faster builds
      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify Gradle wrapper
        run: ./gradlew --no-daemon --version

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/**/*.apk
          if-no-files-found: error
