name: Build Android APK (auto: Gradle or Expo prebuild)

on:
  push:
    branches: [ "ci-build", "main", "master" ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_TELEMETRY: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms/build-tools (explicit)
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Install JS deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Detect android/gradlew
        id: detect
        run: |
          if [ -f android/gradlew ]; then
            echo "mode=gradle" >> "$GITHUB_OUTPUT"
          else
            echo "mode=expo" >> "$GITHUB_OUTPUT"
          fi

      - name: Expo prebuild (Android) if needed
        if: steps.detect.outputs.mode == 'expo'
        run: |
          npx --yes expo@latest prebuild --platform android --no-install --non-interactive
          test -f android/gradlew || (echo "android/gradlew missing after prebuild" && exit 1)

      - name: Print layout
        run: |
          ls -la
          ls -la android || true
          ls -la android/app || true

      - name: Gradle assembleDebug (with stacktrace)
        working-directory: android
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dkotlin.daemon.jvm.options=-Xmx1024m" >> gradle.properties
          ./gradlew --version
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: VerumOmnis-debug-apk
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/**/**/*.apk
          if-no-files-found: warn
