name: Build Android APK (auto: Gradle or Expo prebuild)

on:
  push:
    branches: [ "ci-build", "main", "master" ]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_TELEMETRY: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install JS deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Detect android/gradlew
        id: detect
        run: |
          if [ -f android/gradlew ]; then
            echo "mode=gradle" >> "$GITHUB_OUTPUT"
          else
            echo "mode=expo" >> "$GITHUB_OUTPUT"
          fi

      - name: Build with Gradle (debug)
        if: steps.detect.outputs.mode == 'gradle'
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Expo prebuild (Android) then Gradle
        if: steps.detect.outputs.mode == 'expo'
        run: |
          npx --yes expo@latest prebuild --platform android --no-install --non-interactive
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: VerumOmnis-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
